version: "3.9"

services:

  petstoreapp:
    build:
      context: ./petstoreapp
    ports:
      - "8080:8080"
    environment:
      - PETSTOREAPP_SERVER_PORT=8080
      - PETSTOREPETSERVICE_URL=http://petstorepetservice:8081
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
      - PETSTOREORDERSERVICE_URL=http://petstoreorderservice:8083
    networks:
      - petstorebridge

  petstorepetservice:
    build:
      context: ./petstorepetservice
    ports:
      - "8081:8081"
    environment:
      - PETSTOREPETSERVICE_SERVER_PORT=8081
    networks:
      - petstorebridge

  petstoreproductservice:
    build:
      context: ./petstoreproductservice
    ports:
      - "8082:8082"
    environment:
      - PETSTOREPRODUCTSERVICE_SERVER_PORT=8082
    networks:
      - petstorebridge

  petstoreorderservice:
    build:
      context: ./petstoreorderservice
    ports:
      - "8083:8083"
    environment:
      - PETSTOREORDERSERVICE_SERVER_PORT=8083
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
    networks:
      - petstorebridge

networks:
  petstorebridge:
    driver: bridge
